#!/usr/local/bin/bash

# Tự động phát hiện interface mạng
auto_detect_interface() {
    IFCFG=$(ip -o link show | awk -F': ' '$3 !~ /lo|vir|^[^0-9]/ {print $2; exit}')
}

# Cấu hình tường lửa
gen_iptables() {
    systemctl mask firewalld
    systemctl enable iptables
    systemctl stop firewalld
    yum install iptables-services -y
    systemctl enable iptables
    systemctl start iptables
    systemctl enable ip6tables
    systemctl start ip6tables
    echo "Thiết lập tường lửa...."
}

# Tạo tệp tin ipv6.txt và cấu hình ifconfig cho IPV6
gen_ipv6_64() {
    rm -f $WORKDIR/ipv6.txt
    count_ipv6=1
    while [ "$count_ipv6" -le $MAXCOUNT ]
    do
        array=( 1 2 3 4 5 6 7 8 9 0 a b c d e f )
        ip64() {
            echo "${array[$RANDOM % 16]}${array[$RANDOM % 16]}${array[$RANDOM % 16]}${array[$RANDOM % 16]}"
        }
        echo $IP6:$(ip64):$(ip64):$(ip64):$(ip64) >> $WORKDIR/ipv6.txt
        let "count_ipv6 += 1"
    done

    while read line; do    
        echo "ifconfig $IFCFG inet6 add $line/64"
    done < $WORKDIR/ipv6.txt > $WORKDIR/boot_ifconfig.sh
}

# Cài đặt và cấu hình 3proxy
install_3proxy() {
    echo "Cài đặt 3proxy"
    sudo yum install gcc make nano git -y
    git clone https://github.com/z3apa3a/3proxy
    cd 3proxy
    ln -s Makefile.Linux Makefile
    make
    sudo make install
    systemctl daemon-reload
    echo "* hard nofile 999999" >> /etc/security/limits.conf
    echo "* soft nofile 999999" >> /etc/security/limits.conf
    systemctl stop firewalld
    systemctl disable firewalld
    ulimit -n 65535
    chkconfig 3proxy on
    cd $WORKDIR
}

# Cấu hình file 3proxy.cfg
gen_3proxy_cfg() {
    echo daemon
    echo maxconn 3000
    echo nserver 1.1.1.1
    echo nserver [2606:4700:4700::1111]
    echo nserver [2606:4700:4700::1001]
    echo nserver [2001:4860:4860::8888]
    echo nscache 65536
    echo timeouts 1 5 30 60 180 1800 15 60
    echo setgid 65535
    echo setuid 65535
    echo stacksize 6291456 
    echo flush
    echo authcache user 86400
    echo auth strong cache
    echo "users vlt:CL:vlt"
    echo "allow vlt"
    echo "allow 14.224.163.75"
    port=$START_PORT
    while read ip; do
        echo "proxy -6 -n -a -p$port -i$IP4 -e$ip"
        ((port+=1))
    done < $WORKDIR/ipv6.txt
}

# Tạo và xuất file danh sách proxy
export_txt() {
    port=$START_PORT
    for ((i=1; i<=$MAXCOUNT; i++)); do
        echo "$IP4:$port:vlt:vlt"
        ((port+=1))
    done
}

# Upload file proxy lên server
upload_proxy() {
    cd $WORKDIR || return
    curl -F "file=@proxy.txt" https://file.io
}

# Tạo và cấu hình file xoay.sh
xoay_proxy() {
    cat > xoay.sh << "EOF"
#!/bin/bash

gen_ipv6_64() {
    rm -f $WORKDIR/ipv6.txt
    count_ipv6=1
    while [ "$count_ipv6" -le $MAXCOUNT ]
    do
        array=( 1 2 3 4 5 6 7 8 9 0 a b c d e f )
        ip64() {
            echo "${array[$RANDOM % 16]}${array[$RANDOM % 16]}${array[$RANDOM % 16]}${array[$RANDOM % 16]}"
        }
        echo $IP6:$(ip64):$(ip64):$(ip64):$(ip64) >> $WORKDIR/ipv6.txt
        let "count_ipv6 += 1"
    done
}

# Tạo cấu hình 3proxy
gen_3proxy_cfg() {
    echo "daemon"
    echo "maxconn 10000"
    echo "nserver 1.1.1.1"
    echo "nserver 8.8.4.4"
    echo "nserver [2606:4700:4700::1111]"
    echo "nserver [2606:4700:4700::1001]"
    echo "nserver 2001:4860:4860::8888"
    echo "nserver 2001:4860:4860::8844"
    echo "nscache 65536"
    echo "timeouts 1 5 30 60 180 1800 15 60"
    echo "setgid 65535"
    echo "setuid 65535"
    echo "stacksize 6291456"
    echo "flush"
    echo "auth none"
    echo "allow 127.0.0.1"

    port="$START_PORT"
    while read -r ip; do
        echo "proxy -6 -n -a -p$port -i$IP4 -e$ip"
        ((port+=1))
    done < "$WORKDIR/ipv6.txt"
}

# Tạo lệnh ifconfig cho IPv6
gen_ifconfig() {
    while read -r line; do
        echo "ifconfig $IFCFG inet6 add $line/64"
    done < "$WORKDIR/ipv6.txt"
}

# Xuất cấu hình ra tập tin văn bản
export_txt() {
    port="$START_PORT"
    for ((i=1; i<=$MAXCOUNT; i++)); do
        echo "$IP4:$port"
        ((port+=1))
    done
}


Kiểm tra quyền root và khởi động chính script

if [ “$(id -u)” != ‘0’ ]; then
echo ‘Lỗi: Script này cần chạy với quyền root’
exit 1
fi

Các biến chính

WORKDIR=”/home/proxy”
MAXCOUNT=2000  # Thay thế bằng số lượng IPv6 cần tạo
mkdir -p “$WORKDIR”
chmod -R 777 “$WORKDIR”
auto_detect_interface

Kiểm tra và lấy địa chỉ IPv4 và IPv6

if ping6 -c3 icanhazip.com &> /dev/null; then
IP4=$(curl -s ifconfig.me)
IP6=$(curl -6 -s icanhazip.com | cut -f1-4 -d’:’)
main_interface=$(ip route get 8.8.8.8 | awk ‘{print $5}’)
echo “[OKE]: Thành công”
echo “IPv4: $IP4”
echo “IPv6: $IP6”
echo “Giao diện mạng chính: $main_interface”
else
echo “[ERROR]: Thất bại!”
exit 1
fi

IFCFG=”$main_interface”

Tạo địa chỉ IPv6 và cấu hình

echo “Đang tạo $MAXCOUNT IPv6 > ipv6.txt”
gen_ipv6_64
echo “Đang tạo IPV6 gen_ifconfig.sh”
gen_ifconfig > “$WORKDIR/boot_ifconfig.sh”

Cài đặt 3proxy và cấu hình

systemctl disable –now firewalld
service iptables stop
gen_3proxy_cfg > /etc/3proxy/3proxy.cfg
service 3proxy restart

Xuất cấu hình ra tập tin văn bản

echo “Xuất $IP4.txt”
export_txt > “$WORKDIR/$IP4.txt”

Tạo script xoay để cập nhật địa chỉ IPv6

gen_xoay() {
cat < “$WORKDIR/xoay.sh”
#!/bin/bash
echo “Đang tạo $MAXCOUNT IPv6 > ipv6.txt”
gen_ipv6_64
echo “Đang tạo IPV6 gen_ifconfig.sh”
gen_ifconfig > “$WORKDIR/boot_ifconfig.sh”
echo “Khởi động lại 3proxy”
gen_3proxy_cfg > /etc/3proxy/3proxy.cfg
service 3proxy restart
echo “Đã đặt lại địa chỉ IP”
EOF
chmod +x “$WORKDIR/xoay.sh”
}
gen_xoay

echo “Cấu hình Xoay thành công”

Tự động khởi động 3proxy khi khởi động hệ thống

chmod +x “$WORKDIR/boot_*.sh” /etc/rc.local

cat >>/etc/rc.local <<EOF
#!/bin/bash
systemctl start NetworkManager.service
killall 3proxy
service 3proxy start
bash ${WORKDIR}/boot_iptables.sh
bash ${WORKDIR}/boot_ifconfig.sh
ulimit -n 65535
/usr/local/etc/3proxy/bin/3proxy /usr/local/etc/3proxy/3proxy.cfg &
EOF

install_3proxy
gen_3proxy_cfg
export_txt > $WORKDIR/proxy.txt
xoay_proxy

echo “Tổng số IPv6 hiện tại:”
ip -6 addr | grep inet6 | wc -l
upload_proxy
