#!/bin/bash

# Kiểm tra kết nối mạng
echo "Kiểm tra kết nối mạng..."
ping -c 1 8.8.8.8 >/dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "Không có kết nối mạng. Vui lòng kiểm tra lại kết nối và thử lại sau."
    exit 1
fi

# Lấy tên của card mạng
interface=$(ip link show | awk -F': ' '/^[0-9]+:/ {print $2}')

# Hiển thị tên của card mạng
echo "Tên của card mạng là: $interface"

# Kiểm tra trạng thái giao diện mạng
echo "Kiểm tra trạng thái giao diện mạng $interface..."
if ! ip link show "$interface" >/dev/null 2>&1; then
    echo "Giao diện mạng $interface không hoạt động."
    exit 1
fi

# Lấy địa chỉ IPv6
echo "Lấy địa chỉ IPv6 cho giao diện mạng $interface..."
IP6=$(ip -6 addr show "$interface" | grep -oP '(?<=inet6\s)[\da-f:]+' | grep -v ^::1 | head -n 1)
if [ -z "$IP6" ]; then
    echo "Không thể lấy địa chỉ IPv6 cho giao diện mạng $interface, thử sử dụng phương thức khác."
    IP6=$(curl -6 -s icanhazip.com)
fi

# Kiểm tra nếu không lấy được địa chỉ IPv6
if [ -z "$IP6" ]; then
    echo "Không thể lấy được địa chỉ IPv6 cho giao diện mạng $interface. Vui lòng kiểm tra kết nối mạng và thử lại sau."
    exit 1
fi

# Function to configure IPv6
configure_ipv6() {
    # CentOS configuration
    if [ -f /etc/sysconfig/network-scripts/ifcfg-"$interface" ]; then
        cat <<EOF >/etc/sysconfig/network-scripts/ifcfg-"$interface"
TYPE=Ethernet
NAME=$interface
DEVICE=$interface
ONBOOT=yes
BOOTPROTO=dhcp
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=eui64
IPADDR=$IP4
NETMASK=255.255.255.0
GATEWAY=192.168.1.1
DNS1=8.8.8.8
IPV6ADDR=$IP6/64
IPV6_DEFAULTGW=YOUR_IPV6_GATEWAY
EOF
        service network restart
    # Ubuntu configuration using Netplan
    elif [ -f /etc/netplan/01-netcfg.yaml ]; then
        cat <<EOF >/etc/netplan/01-netcfg.yaml
network:
  version: 2
  ethernets:
    $interface:
      dhcp4: true
      addresses:
        - $IP4/24
        - $IP6/64
      gateway4: 192.168.1.1
      nameservers:
        addresses:
          - 8.8.8.8
          - 2001:4860:4860::8888
      gateway6: 2001:db8:85a3::1
      nameservers:
        addresses:
          - 8.8.8.8
          - 2001:4860:4860::8888
EOF
        sudo netplan apply
    else
        echo "Unsupported OS or missing network configuration files."
        exit 1
    fi

    echo "IPv6 configured as $IP6 for network interface $interface"
}

# Execute function to configure IPv6
configure_ipv6
