#!/bin/bash

# Script tạo proxy IPv6 không yêu cầu mật khẩu

WORKDIR="/home/proxy/"
LOGFILE="${WORKDIR}/ipv6.log"

cat << "EOF"
==========================================================================
        IPv6 All Cloud VPS Server
==========================================================================
EOF

echo "Installing necessary packages and initializing..."

if [[ -f /etc/os-release ]]; then
    . /etc/os-release
    OS=$NAME
    VER=$VERSION_ID
elif type lsb_release >/dev/null 2>&1; then
    OS=$(lsb_release -si)
    VER=$(lsb_release -sr)
elif [[ -f /etc/debian_version ]]; then
    OS="Debian"
    VER=$(cat /etc/debian_version)
elif [[ -f /etc/redhat-release ]]; then
    OS=$(cat /etc/redhat-release | cut -d' ' -f1)
    VER=$(cat /etc/redhat-release | cut -d' ' -f4)
else
    OS=$(uname -s)
    VER=$(uname -r)
fi

if [[ "$OS" = "Ubuntu" || "$OS" = "Debian" ]]; then
    apt-get update
    apt-get install -y subnetcalc psmisc > /dev/null
elif [[ "$OS" = "CentOS" || "$OS" = "Red Hat Enterprise Linux Server" ]]; then
    yum install -y epel-release
    yum install -y subnetcalc psmisc > /dev/null
fi

generateRandomIPv6() {
    prefix=$1
    ipv6mask=$2
    noOfRandomHextet=$(( (128-${ipv6mask}) / 16))
    randomHextet() {
        echo -n "${array[$RANDOM % 16]}${array[$RANDOM % 16]}${array[$RANDOM % 16]}${array[$RANDOM % 16]}"
    }
    echo -n "$1"
    for (( i=0; i<${noOfRandomHextet}; i++ )); do
        echo -n ":$(randomHextet)"
    done
}

setIPv6() {
    ipv6=$1
    ipv6mask=$2
    if [[ "$OS" = "Ubuntu" || "$OS" = "Debian" ]]; then
        if grep -q "iface $network_card inet6 static" /etc/network/interfaces; then
            sed -i "/iface $network_card inet6 static/d" /etc/network/interfaces
        fi
        echo "iface $network_card inet6 static" >> /etc/network/interfaces
        echo "address $ipv6/$ipv6mask" >> /etc/network/interfaces
        service networking restart
    elif [[ "$OS" = "CentOS" || "$OS" = "Red Hat Enterprise Linux Server" ]]; then
        nmcli connection modify "$network_card" ipv6.method manual ipv6.address "$ipv6/$ipv6mask"
        nmcli connection up "$network_card"
    fi
}

getPrefix() {
    ipv6=$1
    ipv6mask=$2
    if [[ $ipv6 && $ipv6mask && $ipv6mask -ge 0 && $ipv6mask -lt 128 ]]; then
        noOfPrefixHextet=$(( $ipv6mask / 16 ))
        for (( i=1; i<=${noOfPrefixHextet}; i++ )); do
            hextet=$(echo $ipv6 | cut -d : -f "$i")
            if [[ $hextet ]]; then
                echo -n "$hextet:"
            else
                echo -n "0000:"
            fi
        done
    fi
}

createProxyIPv6() {
    read -p "Nhập số lượng proxy IPv6 cần tạo: " totalProxy
    if [[ ! $totalProxy =~ ^[1-9][0-9]*$ ]]; then
        echo "Số lượng không hợp lệ. Vui lòng nhập số nguyên dương."
        return 1
    fi

    ipv61=$1
    ipv6range=$2
    ipv6gw=$3
    ipv6sub=$(cut -d / -f 2 <<<$ipv61)

    prefix=$(getPrefix $ipv6gw $ipv6sub)

    array=(1 2 3 4 5 6 7 8 9 0 a b c d e f)

    generateData() {
        currentIPv4=$2
        prefix=$3
        ipv6mask=$4
        for (( i=1; i<=${totalProxy}; i++ )); do
            randomIPv6=$(generateRandomIPv6 $prefix $ipv6mask)
            setIPv6 $randomIPv6 $ipv6mask
            echo "Proxy IPv6 $i: $randomIPv6"
        done
    }

    echo "Creating $totalProxy IPv6 proxies without password authentication..."
    generateData 1000 192.168.1.151 $prefix $ipv6sub

    echo "Proxy IPv6 đã được tạo mà không yêu cầu mật khẩu."
}

# Menu selection
PS3='Chọn một tác vụ để thực hiện: '
options=("Tạo proxy IPv6 không yêu cầu mật khẩu" "Thoát")
select opt in "${options[@]}"
do
    case $opt in
        "Tạo proxy IPv6 không yêu cầu mật khẩu")
            createProxyIPv6
            ;;
        "Thoát")
            break
            ;;
        *) echo "Lựa chọn không hợp lệ";;
    esac
done
